info:
  app:
    description: Traffic congestions monitor base on Google Map Platform API


# GOOGLE MAP PLATFORM PROPERTIES
# ------------------------------
google:
  map:
    baseurl: "https://maps.googleapis.com/"
    actionurl: "https://www.google.com/"
    apikey: ${GOOGLE_MAP_APIKEY}


# WEB API PROPERTIES
# ------------------
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css


# SPRING CUSTOM PROPERTIES
# ------------------------
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: trafimon
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_AUTH_CLIENT_ID}
            client-secret: ${GOOGLE_AUTH_CLIENT_SECRET}
